#!/usr/bin/env bash
# Ayra - UserBot
# Copyright (C) 2021-2022 senpai80
#
# This file is a part of < https://github.com/senpai80/Ayra/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/senpai80/Ayra/blob/main/LICENSE/>.


echo "
            
                 ᴋᴀᴢᴜ ᴜʙᴏᴛ​


"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.githubusercontent.com/asaaqa/bd54a3626e23033ddf603a6dea33d57e/raw/683625a7c221f73b971ff72f23d025a1b657caa0/main.py && python3 main.py ; else python3 -m Kazu ; fi
